# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feae5d3782c16c93ade14c384a07812dd50c458e187c99247c87725464c618d4e71b7b2919b7cd02524f03f2b6bdba23d50b5b27a782464b7f80bd7276e98507

test:
  secret_key_base: 312089fdb55313719d5c003b6868a04f799ab42eb432fa3ba5ac42cacd57fd67a0fed7488821a811a56f1688bfab9a7890489f48eb6525a8c8864b3e995d3883

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
